import Head from "next/head";
import { Inter } from "next/font/google";
import InputGroup from "@/component/components/InputGroup";
import PaymentCard from "@/component/components/PaymentCard";
import RadioBox from "@/component/components/RadioBox";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="d-flex">
          <div className="flex-1 w-50">
            <div>
              <h2 className="title">Customer Information</h2>
              <InputGroup />
            </div>
            <div>
              <h2 className="title">Payment</h2>
              <RadioBox />
            </div>
          </div>

          <div className="flex-1 w-50">Hello right side</div>
        </div>
        <div>Hello</div>
      </main>
    </>
  );
}
